# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{engine-assets}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Corey Innis"]
  s.date = %q{2009-11-06}
  s.description = %q{A Rails Engine, which enables Rails Engines to provide assets (javascript, css and images)}
  s.email = %q{support@coolerator.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO.md",
     "VERSION",
     "app/controllers/engine_assets/assets_controller.rb",
     "app/controllers/engine_assets/javascripts_controller.rb",
     "app/controllers/engine_assets/stylesheets_controller.rb",
     "config/routes.rb",
     "lib/engine-assets.rb",
     "lib/engine_assets/extensions/rails/routes.rb",
     "lib/engine_assets/public_locator.rb",
     "rails/init.rb",
     "spec/routing/javascripts_routing_spec.rb",
     "spec/routing/stylesheets_routing_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/spec_suite.rb",
     "spec/support/fixtures/app/views/javascripts/asset.js.erb",
     "spec/support/fixtures/public/javascripts/asset.js",
     "spec/support/helpers/textmate_helper.rb"
  ]
  s.homepage = %q{http://github.com/coreyti/engine-assets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails Engines with assets.}
  s.test_files = [
    "spec/routing/javascripts_routing_spec.rb",
     "spec/routing/stylesheets_routing_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_suite.rb",
     "spec/support/helpers/textmate_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

